name: Create Testing Container

on:
    push:
        branches: [testing]

jobs:
    build-app:
        name: Build Testing Container
        runs-on: ubuntu-latest
        env:
            TAG: loadorderlibrary-next
            REGISTRY: ghcr.io
            VERSION: testing
        steps:
            - uses: actions/checkout@main

            # Creating as .production to ensure vite defaults to that.
            - name: Create .env file
              run: |
                  touch .env.production
                  echo VITE_APP_TITLE="${{ secrets.TESTING_APP_TITLE }}" >> .env
                  echo VITE_API_URL="${{ secrets.TESTING_API_URL }}" >> .env

            - name: Build Container Image
              run: docker build --target app-testing -t $TAG -f docker/testing/app/Dockerfile .

            - name: Push to GHCR
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
                  docker tag $TAG ${{ env.REGISTRY }}/${{ secrets.OWNER_LC }}/$TAG:${{ env.VERSION }}
                  docker push ${{ env.REGISTRY }}/${{ secrets.OWNER_LC }}/$TAG:${{ env.VERSION }}

    # deploy:
    #     name: Deploy Container to Server
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #         - name: SSH and deploy?
    #           run: |
    #               echo "${{ secrets.KEY }}" > id_meow
    #               chmod 600 id_meow
    #               ssh -i id_meow "${{ secrets.USERNAME }}"@"${{ secrets.HOST }}" -o "StrictHostKeyChecking no" "sudo /opt/lol/deploy_lolapi-testing.sh"
